import './globals.css'
import styles from './styles.module.css';
import { Inter } from 'next/font/google'
import Link from "next/link"
import { ReactChildren, StrictMode } from 'react'
import Providers from './provider'
import { BodyLayout } from '@/component/layout'
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div>
          <StrictMode>
            <Providers>
              <BodyLayout>
                {children}
              </BodyLayout>
            </Providers>
          </StrictMode>
        </div>
      </body>
    </html>
  )
}

